import { AMBIGUITY_STATUS_LABELS, SPEC_SECTIONS, type StrategyDefinition } from "./strategy-schema";
import { validateDefinition } from "./validation";

export function toMarkdown(
  def: StrategyDefinition,
  meta: { name: string; sourceType: string; updatedAt?: string },
): string {
  const result = validateDefinition(def);
  const lines: string[] = [];

  lines.push(`# ${meta.name}`);
  lines.push("");
  lines.push(`_Strategy Definition generated by the Trading Strategy Specification Engine._`);
  lines.push("");
  lines.push(`- Source type: ${meta.sourceType}`);
  if (meta.updatedAt) lines.push(`- Last updated: ${meta.updatedAt}`);
  lines.push("");
  lines.push("## Scores");
  lines.push("");
  lines.push("| Metric | Score |");
  lines.push("| --- | --- |");
  lines.push(`| Completeness | ${result.completeness}% |`);
  lines.push(`| Determinism | ${result.determinism}% |`);
  lines.push(`| Ambiguity resolution | ${result.ambiguity}% |`);
  lines.push(`| Execution confidence | ${result.executionConfidence}% |`);
  lines.push("");

  for (const section of SPEC_SECTIONS) {
    lines.push(`## ${section.index}. ${section.title}`);
    lines.push("");
    for (const field of section.fields) {
      const value = (def.sections[section.key]?.[field.key] ?? "").trim();
      if (field.rule && value) {
        lines.push(`**${field.label}**`);
        lines.push("");
        lines.push("```");
        lines.push(value);
        lines.push("```");
        lines.push("");
      } else {
        lines.push(`- **${field.label}:** ${value || "_not specified_"}`);
      }
    }
    lines.push("");
  }

  lines.push(`## ${SPEC_SECTIONS.length + 1}. Assumptions`);
  lines.push("");
  if (def.assumptions.length === 0) {
    lines.push("_No assumptions recorded._");
  } else {
    lines.push("| Term | Interpretation | Confidence |");
    lines.push("| --- | --- | --- |");
    for (const a of def.assumptions) {
      lines.push(`| ${a.term} | \`${a.interpretation}\` | ${a.confidence}% |`);
    }
  }
  lines.push("");

  lines.push(`## ${SPEC_SECTIONS.length + 2}. Ambiguities`);
  lines.push("");
  if (def.ambiguities.length === 0) {
    lines.push("_No ambiguities recorded._");
  } else {
    lines.push("| Item | Status | Note |");
    lines.push("| --- | --- | --- |");
    for (const a of def.ambiguities) {
      lines.push(`| ${a.item} | ${AMBIGUITY_STATUS_LABELS[a.status]} | ${a.note} |`);
    }
  }
  lines.push("");

  lines.push(`## ${SPEC_SECTIONS.length + 3}. Validation`);
  lines.push("");
  if (result.missing.length > 0) {
    lines.push("**Missing required fields**");
    lines.push("");
    for (const m of result.missing) lines.push(`- ${m.section} → ${m.field}`);
    lines.push("");
  }
  const errors = result.issues.filter((i) => i.level === "error");
  const warnings = result.issues.filter((i) => i.level === "warning");
  const suggestions = result.issues.filter((i) => i.level === "suggestion");
  for (const [label, group] of [
    ["Errors", errors],
    ["Warnings", warnings],
    ["Suggestions", suggestions],
  ] as const) {
    lines.push(`**${label}**`);
    lines.push("");
    if (group.length === 0) lines.push("- None");
    for (const issue of group) lines.push(`- ${issue.section}: ${issue.message}`);
    lines.push("");
  }

  return lines.join("\n");
}
