/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as StrategiesIdRouteImport } from './routes/strategies/$id'
import { Route as StrategiesNewRouteImport } from './routes/strategies/new'
import { Route as ApiPublicBacktestCallbackRouteImport } from './routes/api/public/backtest-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIdRoute = StrategiesIdRouteImport.update({
  id: '/strategies/$id',
  path: '/strategies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesNewRoute = StrategiesNewRouteImport.update({
  id: '/strategies/new',
  path: '/strategies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBacktestCallbackRoute =
  ApiPublicBacktestCallbackRouteImport.update({
    id: '/api/public/backtest-callback',
    path: '/api/public/backtest-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/api/public/backtest-callback': typeof ApiPublicBacktestCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/datasets': typeof DatasetsIndexRoute
  '/api/public/backtest-callback': typeof ApiPublicBacktestCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/api/public/backtest-callback': typeof ApiPublicBacktestCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/strategies/$id'
    | '/strategies/new'
    | '/datasets/'
    | '/api/public/backtest-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/strategies/$id'
    | '/strategies/new'
    | '/datasets'
    | '/api/public/backtest-callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/strategies/$id'
    | '/strategies/new'
    | '/datasets/'
    | '/api/public/backtest-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StrategiesIdRoute: typeof StrategiesIdRoute
  StrategiesNewRoute: typeof StrategiesNewRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ApiPublicBacktestCallbackRoute: typeof ApiPublicBacktestCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$id': {
      id: '/strategies/$id'
      path: '/strategies/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof StrategiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/new': {
      id: '/strategies/new'
      path: '/strategies/new'
      fullPath: '/strategies/new'
      preLoaderRoute: typeof StrategiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backtest-callback': {
      id: '/api/public/backtest-callback'
      path: '/api/public/backtest-callback'
      fullPath: '/api/public/backtest-callback'
      preLoaderRoute: typeof ApiPublicBacktestCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StrategiesIdRoute: StrategiesIdRoute,
  StrategiesNewRoute: StrategiesNewRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ApiPublicBacktestCallbackRoute: ApiPublicBacktestCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
